apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-buddy
  labels:
    app: travel-buddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-buddy
  template:
    metadata:
      name: travel-buddy
      labels:
        app: travel-buddy
    spec:
      containers:
        - name: timetable-service
          image: ghcr.io/prpo-projekt/timetable-service:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
        - name: routing-service
          image: ghcr.io/prpo-projekt/routing-service:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
        - name: crowdsourcing-service
          image: ghcr.io/prpo-projekt/crowdsourcing-service:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: prpo-db
                  key: db-pass
      restartPolicy: Always
      