apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-buddy
  labels:
    app: travel-buddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-buddy
  template:
    metadata:
      name: travel-buddy
      labels:
        app: travel-buddy
    spec:
      containers:
        - name: timetable-service
          image: ghcr.io/prpo-projekt/timetable-service:main
          imagePullPolicy: Always
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: prpo-db
                  key: db-pass
        - name: routing-service
          image: ghcr.io/prpo-projekt/routing-service:main
          imagePullPolicy: Always
        - name: crowdsourcing-service
          image: ghcr.io/prpo-projekt/crowdsourcing-service:main
          imagePullPolicy: Always
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: prpo-db
                  key: db-pass
        - name: poi-service
          image: ghcr.io/prpo-projekt/poi-service:main
          imagePullPolicy: Always
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                 name: prpo-db
                 key: db-pass
        - name: account-manager-service
          image: ghcr.io/prpo-projekt/account-manager-service:main
          imagePullPolicy: Always
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: prpo-db
                  key: db-pass
        - name: user-manager-service
          image: ghcr.io/prpo-projekt/user-manager-service:main
          imagePullPolicy: Always
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: prpo-db
                  key: db-pass
        - name: ticket-search-service
          image: ghcr.io/prpo-projekt/ticket-search-service:main
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 8093
              path: /health
            initialDelaySeconds: 120
            periodSeconds: 5
        - name: purchase-service
          image: ghcr.io/prpo-projekt/purchase-service:main
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 8094
              path: /health
            initialDelaySeconds: 120
            periodSeconds: 5
      restartPolicy: Always
      
