apiVersion: v1
kind: Service
metadata:
  name: travel-buddy
spec:
  selector:
    app: travel-buddy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: timetable-service
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: routing-service
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: crowdsourcing-service
    - protocol: TCP
      port: 8090
      targetPort: 8090
      name: poi-service
    - protocol: TCP
      port: 8091
      targetPort: 8091
      name: account-manager-service
    - protocol: TCP
      port: 8092
      targetPort: 8092
      name: user-manager-service
    - protocol: TCP
      port: 8093
      targetPort: 8093
      name: ticket-search-service
  type: LoadBalancer
  