apiVersion: v1
kind: Service
metadata:
  name: travel-buddy
spec:
  selector:
    app: travel-buddy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 8081
      targetPort: 8081
    - protocol: TCP
      port: 8082
      targetPort: 8082
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer
  