openapi: "3.1.0"
info:
  title: "travel_buddy API"
  description: "travel_buddy API"
  version: "1.0.0"
servers:
- url: "/"
paths:
  /delay:
    get:
      description: ""
      parameters:
      - name: "stopId"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DepartureDelay"
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DepartureDelayDto"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"
  /delay/{id}:
    get:
      description: ""
      parameters:
      - name: "stopId"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "integer"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Object"
  /delay/average:
    get:
      description: ""
      parameters:
      - name: "stopId"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "number"
                format: "double"
components:
  schemas:
    DepartureDelay:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        delay:
          type: "integer"
          format: "int64"
        userId:
          type: "string"
        stopId:
          type: "string"
      required:
      - "id"
      - "delay"
      - "stopId"
    DepartureDelayDto:
      type: "object"
      properties:
        delay:
          type: "string"
        userId:
          type: "string"
        stopId:
          type: "string"
      required:
      - "delay"
      - "userId"
      - "stopId"
    Object:
      type: "object"
      properties: {}