apiVersion: v1
kind: Service
metadata:
  name: user-manager-service
spec:
  selector:
    app: travel-buddy
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
  