kumuluzee:
  name: "travel-buddy-ticket-search"
  version: "0.0.1"
  env: "dev"
  datasources:
    - name: TicketsDS
      jndi-name: jdbc/Tickets
      connection-url: jdbc:postgresql://traverl-buddy.postgres.database.azure.com:5432/prpo
      username: prpo
      password: ,7D9gJ7dujv'ZP_